import { HolidayType } from "./enums"

export const cantons = {
    ag: "Aargau",
    ar: "Appenzell Ausserrhoden",
    ai: "Appenzell Innerrhoden",
    bl: "Basel-Landschaft",
    bs: "Basel-Stadt",
    be: "Bern",
    fr: "Freiburg",
    ge: "Genf",
    gl: "Glarus",
    gr: "Graubünden",
    ju: "Jura",
    lu: "Luzern",
    ne: "Neuenburg",
    nw: "Nidwalden",
    ow: "Obwalden",
    sh: "Schaffhausen",
    sz: "Schwyz",
    so: "Solothurn",
    sg: "St. Gallen",
    ti: "Tessin",
    tg: "Thurgau",
    ur: "Uri",
    vd: "Waadt",
    vs: "Wallis",
    zg: "Zug",
    zh: "Zürich"
}

export const holidayTypes: Record<string, string> = {
    by_law: "gesetzlich",
    optional: "optional",
    partly_by_law: "teils gesetzlich"
}

type CantonHolidaysType = Record<string, Array<{ name: string; date: string | null; type: HolidayType }>>

export const cantonHolidays: CantonHolidaysType = {
    ag: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.partly_by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.partly_by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.partly_by_law }
    ],
    ar: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    ai: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    bl: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    bs: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    be: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    fr: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.partly_by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    ge: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    gl: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    gr: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.partly_by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    ju: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    lu: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Josefstag", date: "03-19", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    ne: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    nw: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    ow: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    sh: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    sz: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    so: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.partly_by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.partly_by_law }
    ],
    sg: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    ti: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    tg: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    ur: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    vd: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    vs: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    zg: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Josefstag", date: "03-19", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    zh: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ]
}

type NationHolidaysType = Array<{ name: string; date: string | null; type: HolidayType }>

export const nationalHolidays: NationHolidaysType = [
    { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
    { name: "Karfreitag", date: null, type: HolidayType.partly_by_law },
    { name: "Auffahrt", date: null, type: HolidayType.by_law },
    { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
    { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
]

export class Email {
    static general = "mail@andrin.software"
}
