import { HolidayType } from "./enums"

export const cantons = {
    aargau: "Aargau",
    "appenzell-ausserrhoden": "Appenzell Ausserrhoden",
    "appenzell-innerrhoden": "Appenzell Innerrhoden",
    "basel-landschaft": "Basel-Landschaft",
    "basel-stadt": "Basel-Stadt",
    bern: "Bern",
    freiburg: "Freiburg",
    genf: "Genf",
    glarus: "Glarus",
    graubuenden: "Graubünden",
    jura: "Jura",
    luzern: "Luzern",
    neuenburg: "Neuenburg",
    nidwalden: "Nidwalden",
    obwalden: "Obwalden",
    schaffhausen: "Schaffhausen",
    schwyz: "Schwyz",
    solothurn: "Solothurn",
    "st-gallen": "St. Gallen",
    tessin: "Tessin",
    thurgau: "Thurgau",
    uri: "Uri",
    waadt: "Waadt",
    wallis: "Wallis",
    zug: "Zug",
    zuerich: "Zürich"
}

export const munics = {
    aargau: {
        aarau: "Aarau",
        aarburg: "Aarburg",
        abtwil: "Abtwil",
        ammerswil: "Ammerswil",
        aristau: "Aristau",
        arni: "Arni",
        auenstein: "Auenstein",
        auw: "Auw",
        baden: "Baden",
        "beinwil-freiamt": "Beinwil (Freiamt)",
        "beinwil-am-see": "Beinwil am See",
        bellikon: "Bellikon",
        bergdietikon: "Bergdietikon",
        berikon: "Berikon",
        besenbueren: "Besenbüren",
        bettwil: "Bettwil",
        biberstein: "Biberstein",
        birmenstorf: "Birmenstorf",
        birr: "Birr",
        birrhard: "Birrhard",
        birrwil: "Birrwil",
        boniswil: "Boniswil",
        boswil: "Boswil",
        bottenwil: "Bottenwil",
        boettstein: "Böttstein",
        boezberg: "Bözberg",
        boeztal: "Böztal",
        bremgarten: "Bremgarten",
        brittnau: "Brittnau",
        brugg: "Brugg",
        brunegg: "Brunegg",
        buchs: "Buchs",
        buenzen: "Bünzen",
        buettikon: "Büttikon",
        buttwil: "Buttwil",
        densbueren: "Densbüren",
        dietwil: "Dietwil",
        dintikon: "Dintikon",
        dottikon: "Dottikon",
        doettingen: "Döttingen",
        duerrenaesch: "Dürrenäsch",
        eggenwil: "Eggenwil",
        egliswil: "Egliswil",
        ehrendingen: "Ehrendingen",
        eiken: "Eiken",
        endingen: "Endingen",
        ennetbaden: "Ennetbaden",
        erlinsbach: "Erlinsbach",
        fahrwangen: "Fahrwangen",
        "fischbach-goeslikon": "Fischbach-Göslikon",
        fisibach: "Fisibach",
        fislisbach: "Fislisbach",
        freienwil: "Freienwil",
        frick: "Frick",
        "full-reuenthal": "Full-Reuenthal",
        gansingen: "Gansingen",
        gebenstorf: "Gebenstorf",
        geltwil: "Geltwil",
        "gipf-oberfrick": "Gipf-Oberfrick",
        gontenschwil: "Gontenschwil",
        graenichen: "Gränichen",
        habsburg: "Habsburg",
        haegglingen: "Hägglingen",
        hallwil: "Hallwil",
        hausen: "Hausen",
        hellikon: "Hellikon",
        hendschiken: "Hendschiken",
        "herznach-ueken": "Herznach-Ueken",
        hirschthal: "Hirschthal",
        "holderbank-la": "Holderbank",
        holziken: "Holziken",
        hunzenschwil: "Hunzenschwil",
        islisberg: "Islisberg",
        jonen: "Jonen",
        kaiseraugst: "Kaiseraugst",
        kaisten: "Kaisten",
        kallern: "Kallern",
        killwangen: "Killwangen",
        kirchleerau: "Kirchleerau",
        klingnau: "Klingnau",
        koblenz: "Koblenz",
        koelliken: "Kölliken",
        kuenten: "Künten",
        kuettigen: "Küttigen",
        laufenburg: "Laufenburg",
        leibstadt: "Leibstadt",
        leimbach: "Leimbach",
        lengnau: "Lengnau",
        lenzburg: "Lenzburg",
        leuggern: "Leuggern",
        leutwil: "Leutwil",
        lupfig: "Lupfig",
        magden: "Magden",
        maegenwil: "Mägenwil",
        mandach: "Mandach",
        meisterschwanden: "Meisterschwanden",
        mellikon: "Mellikon",
        mellingen: "Mellingen",
        menziken: "Menziken",
        merenschwand: "Merenschwand",
        mettauertal: "Mettauertal",
        moehlin: "Möhlin",
        moenthal: "Mönthal",
        moosleerau: "Moosleerau",
        "moeriken-wildegg": "Möriken-Wildegg",
        muhen: "Muhen",
        muehlau: "Mühlau",
        muelligen: "Mülligen",
        mumpf: "Mumpf",
        muenchwilen: "Münchwilen",
        murgenthal: "Murgenthal",
        muri: "Muri",
        neuenhof: "Neuenhof",
        niederlenz: "Niederlenz",
        niederrohrdorf: "Niederrohrdorf",
        niederwil: "Niederwil",
        oberentfelden: "Oberentfelden",
        oberhof: "Oberhof",
        oberkulm: "Oberkulm",
        oberlunkhofen: "Oberlunkhofen",
        obermumpf: "Obermumpf",
        oberrohrdorf: "Oberrohrdorf",
        oberrueti: "Oberrüti",
        obersiggenthal: "Obersiggenthal",
        "oberwil-lieli": "Oberwil-Lieli",
        oeschgen: "Oeschgen",
        oftringen: "Oftringen",
        olsberg: "Olsberg",
        othmarsingen: "Othmarsingen",
        reinach: "Reinach",
        reitnau: "Reitnau",
        remetschwil: "Remetschwil",
        remigen: "Remigen",
        rheinfelden: "Rheinfelden",
        riniken: "Riniken",
        rothrist: "Rothrist",
        rottenschwil: "Rottenschwil",
        "rudolfstetten-friedlisberg": "Rudolfstetten‑Friedlisberg",
        ruefenach: "Rüfenach",
        rupperswil: "Rupperswil",
        safenwil: "Safenwil",
        sarmenstorf: "Sarmenstorf",
        schafisheim: "Schafisheim",
        schinznach: "Schinznach",
        schlossrued: "Schlossrued",
        schmiedrued: "Schmiedrued",
        schneisingen: "Schneisingen",
        schoeftland: "Schöftland",
        schupfart: "Schupfart",
        schwaderloch: "Schwaderloch",
        seengen: "Seengen",
        seon: "Seon",
        siglistorf: "Siglistorf",
        sins: "Sins",
        sisseln: "Sisseln",
        spreitenbach: "Spreitenbach",
        staffelbach: "Staffelbach",
        staufen: "Staufen",
        stein: "Stein",
        stetten: "Stetten",
        strengelbach: "Strengelbach",
        suhr: "Suhr",
        taegerig: "Tägerig",
        tegerfelden: "Tegerfelden",
        teufenthal: "Teufenthal",
        thalheim: "Thalheim",
        uerkheim: "Uerkheim",
        uezwil: "Uezwil",
        unterentfelden: "Unterentfelden",
        unterkulm: "Unterkulm",
        unterlunkhofen: "Unterlunkhofen",
        untersiggenthal: "Untersiggenthal",
        veltheim: "Veltheim",
        villigen: "Villigen",
        villmergen: "Villmergen",
        villnachern: "Villnachern",
        vordemwald: "Vordemwald",
        wallbach: "Wallbach",
        waltenschwil: "Waltenschwil",
        wegenstetten: "Wegenstetten",
        wettingen: "Wettingen",
        widen: "Widen",
        wiliberg: "Wiliberg",
        windisch: "Windisch",
        wittnau: "Wittnau",
        wohlen: "Wohlen",
        wohlenschwil: "Wohlenschwil",
        woelflinswil: "Wölflinswil",
        wuerenlingen: "Würenlingen",
        wuerenlos: "Würenlos",
        zeihen: "Zeihen",
        zeiningen: "Zeiningen",
        zetzwil: "Zetzwil",
        zofingen: "Zofingen",
        zufikon: "Zufikon",
        zurzach: "Zurzach",
        zuzgen: "Zuzgen"
    },
    "appenzell-ausserrhoden": {},
    "appenzell-innerrhoden": {},
    "basel-landschaft": {},
    "basel-stadt": {},
    bern: {},
    freiburg: {},
    genf: {},
    glarus: {},
    graubuenden: {},
    jura: {},
    luzern: {},
    neuenburg: {},
    nidwalden: {},
    obwalden: {},
    schaffhausen: {},
    schwyz: {},
    solothurn: {},
    "st-gallen": {},
    tessin: {},
    thurgau: {},
    uri: {},
    waadt: {},
    wallis: {},
    zug: {},
    zuerich: {}
}

export const holidayTypes: Record<string, string> = {
    by_law: "gesetzlich",
    optional: "optional",
    partly_by_law: "teils gesetzlich"
}

type CantonHolidaysType = Record<string, Array<{ name: string; date: string | null; type: HolidayType }>>

export const cantonHolidays: CantonHolidaysType = {
    aargau: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.partly_by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.partly_by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.partly_by_law }
    ],
    "appenzell-ausserrhoden": [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    "appenzell-innerrhoden": [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "St. Mauritiustag", date: "09-22", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    "basel-landschaft": [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Fasnacht", date: null, type: HolidayType.partly_by_law },
        { name: "Fasnachtsmittwoch", date: null, type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    "basel-stadt": [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Fasnacht", date: null, type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    bern: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    freiburg: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.partly_by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    genf: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Genfer Bettag", date: null, type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Wiederherstellung der Republik Genf", date: "12-31", type: HolidayType.by_law }
    ],
    glarus: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Näfelser Fahrt", date: null, type: HolidayType.by_law },
        { name: "Fasnachtsmontag", date: null, type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    graubuenden: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.partly_by_law },
        { name: "St. Josef", date: "03-19", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    jura: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Aschermittwoch", date: null, type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Fest der Unabhängigkeit Jura", date: "06-23", type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    luzern: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Fasnachtsmontag", date: null, type: HolidayType.optional },
        { name: "St. Josef", date: "03-19", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "St. Leodegar", date: "10-02", type: HolidayType.partly_by_law },
        { name: "Gallustag", date: "10-16", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "St. Martin", date: "11-11", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    neuenburg: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Jahrestag der Ausrufung der Republik Neuenburg", date: "03-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Bettagsmontag", date: null, type: HolidayType.optional },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    nidwalden: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "St. Josef", date: "03-19", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    obwalden: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "St. Benediktstag", date: "03-21", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "St. Niklaus von Flüe", date: "09-25", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    schaffhausen: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    schwyz: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.by_law },
        { name: "St. Meinradstag", date: "01-21", type: HolidayType.partly_by_law },
        { name: "Fasnachtsmontag", date: null, type: HolidayType.optional },
        { name: "Fasnachtsdienstag", date: null, type: HolidayType.optional },
        { name: "St. Josef", date: "03-19", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Engelweihe", date: "09-14", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "St. Martin", date: "11-11", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    solothurn: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Fest des hl. Sebastian", date: "01-20", type: HolidayType.partly_by_law },
        { name: "St. Josef", date: "03-19", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.partly_by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "St. Urs und Viktor", date: "09-30", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.partly_by_law }
    ],
    "st-gallen": [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    tessin: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.by_law },
        { name: "Aschermittwoch", date: null, type: HolidayType.partly_by_law },
        { name: "St. Josef", date: "03-19", type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "St. Peter und Paul", date: "06-29", type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    thurgau: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    uri: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.by_law },
        { name: "St. Agatha", date: "02-05", type: HolidayType.partly_by_law },
        { name: "St. Josef", date: "03-19", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    waadt: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Bettagsmontag", date: null, type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    wallis: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "St. Josef", date: "03-19", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam (Herrgottstag)", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    zug: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    zuerich: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ]
}

type NationHolidaysType = Array<{ name: string; date: string | null; type: HolidayType }>

export const nationalHolidays: NationHolidaysType = [
    { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
    { name: "Karfreitag", date: null, type: HolidayType.partly_by_law },
    { name: "Auffahrt", date: null, type: HolidayType.by_law },
    { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
    { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
]

type MunicHolidaysType = Record<
    string,
    Record<string, Array<{ name: string; date: string | null; type: HolidayType }>>
>

export const municHolidays: MunicHolidaysType = {
    aargau: {
        aarau: [
            { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
            { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
            { name: "Karfreitag", date: null, type: HolidayType.by_law },
            { name: "Ostermontag", date: null, type: HolidayType.by_law },
            { name: "Auffahrt", date: null, type: HolidayType.by_law },
            { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
            { name: "Maienzug", date: null, type: HolidayType.optional },
            { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
            { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
            { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
        ],
        aarburg: [],
        abtwil: [],
        ammerswil: [],
        aristau: [],
        arni: [],
        auenstein: [],
        auw: [],
        baden: [],
        "beinwil-freiamt": [],
        "beinwil-am-see": [],
        bellikon: [],
        bergdietikon: [],
        berikon: [],
        besenbueren: [],
        bettwil: [],
        biberstein: [],
        birmenstorf: [],
        birr: [],
        birrhard: [],
        birrwil: [],
        boniswil: [],
        boswil: [],
        bottenwil: [],
        boettstein: [],
        boezberg: [],
        boeztal: [],
        bremgarten: [],
        brittnau: [],
        brugg: [],
        brunegg: [],
        buchs: [],
        buenzen: [],
        buettikon: [],
        buttwil: [],
        densbueren: [],
        dietwil: [],
        dintikon: [],
        dottikon: [],
        doettingen: [],
        duerrenaesch: [],
        eggenwil: [],
        egliswil: [],
        ehrendingen: [],
        eiken: [],
        endingen: [],
        ennetbaden: [],
        erlinsbach: [],
        fahrwangen: [],
        "fischbach-goeslikon": [],
        fisibach: [],
        fislisbach: [],
        freienwil: [],
        frick: [],
        "full-reuenthal": [],
        gansingen: [],
        gebenstorf: [],
        geltwil: [],
        "gipf-oberfrick": [],
        gontenschwil: [],
        graenichen: [],
        habsburg: [],
        haegglingen: [],
        hallwil: [],
        hausen: [],
        hellikon: [],
        hendschiken: [],
        "herznach-ueken": [],
        hirschthal: [],
        "holderbank-la": [],
        holziken: [],
        hunzenschwil: [],
        islisberg: [],
        jonen: [],
        kaiseraugst: [],
        kaisten: [],
        kallern: [],
        killwangen: [],
        kirchleerau: [],
        klingnau: [],
        koblenz: [],
        koelliken: [],
        kuenten: [],
        kuettigen: [],
        laufenburg: [],
        leibstadt: [],
        leimbach: [],
        lengnau: [],
        lenzburg: [],
        leuggern: [],
        leutwil: [],
        lupfig: [],
        magden: [],
        maegenwil: [],
        mandach: [],
        meisterschwanden: [],
        mellikon: [],
        mellingen: [],
        menziken: [],
        merenschwand: [],
        mettauertal: [],
        moehlin: [],
        moenthal: [],
        moosleerau: [],
        "moeriken-wildegg": [],
        muhen: [],
        muehlau: [],
        muelligen: [],
        mumpf: [],
        muenchwilen: [],
        murgenthal: [],
        muri: [],
        neuenhof: [],
        niederlenz: [],
        niederrohrdorf: [],
        niederwil: [],
        oberentfelden: [],
        oberhof: [],
        oberkulm: [],
        oberlunkhofen: [],
        obermumpf: [],
        oberrohrdorf: [],
        oberrueti: [],
        obersiggenthal: [],
        "oberwil-lieli": [],
        oeschgen: [],
        oftringen: [],
        olsberg: [],
        othmarsingen: [],
        reinach: [],
        reitnau: [],
        remetschwil: [],
        remigen: [],
        rheinfelden: [],
        riniken: [],
        rothrist: [],
        rottenschwil: [],
        "rudolfstetten-friedlisberg": [],
        ruefenach: [],
        rupperswil: [],
        safenwil: [],
        sarmenstorf: [],
        schafisheim: [],
        schinznach: [],
        schlossrued: [],
        schmiedrued: [],
        schneisingen: [],
        schoeftland: [],
        schupfart: [],
        schwaderloch: [],
        seengen: [],
        seon: [],
        siglistorf: [],
        sins: [],
        sisseln: [],
        spreitenbach: [],
        staffelbach: [],
        staufen: [],
        stein: [],
        stetten: [],
        strengelbach: [],
        suhr: [],
        taegerig: [],
        tegerfelden: [],
        teufenthal: [],
        thalheim: [],
        uerkheim: [],
        uezwil: [],
        unterentfelden: [],
        unterkulm: [],
        unterlunkhofen: [],
        untersiggenthal: [],
        veltheim: [],
        villigen: [],
        villmergen: [],
        villnachern: [],
        vordemwald: [],
        wallbach: [],
        waltenschwil: [],
        wegenstetten: [],
        wettingen: [],
        widen: [],
        wiliberg: [],
        windisch: [],
        wittnau: [],
        wohlen: [],
        wohlenschwil: [],
        woelflinswil: [],
        wuerenlingen: [],
        wuerenlos: [],
        zeihen: [],
        zeiningen: [],
        zetzwil: [],
        zofingen: [],
        zufikon: [],
        zurzach: [],
        zuzgen: []
    },
    "appenzell-ausserrhoden": { "": [] },
    "appenzell-innerrhoden": { "": [] },
    "basel-landschaft": { "": [] },
    "basel-stadt": { "": [] },
    bern: { "": [] },
    freiburg: { "": [] },
    genf: { "": [] },
    glarus: { "": [] },
    graubuenden: { "": [] },
    jura: { "": [] },
    luzern: { "": [] },
    neuenburg: { "": [] },
    nidwalden: { "": [] },
    obwalden: { "": [] },
    schaffhausen: { "": [] },
    schwyz: { "": [] },
    solothurn: { "": [] },
    "st-gallen": { "": [] },
    tessin: { "": [] },
    thurgau: { "": [] },
    uri: { "": [] },
    waadt: { "": [] },
    wallis: { "": [] },
    zug: { "": [] },
    zuerich: { "": [] }
}

export class Email {
    static general = "mail@andrin.software"
}
