import { HolidayType } from "./enums"

export const cantons = {
    AG: "Aargau",
    AR: "Appenzell Ausserrhoden",
    AI: "Appenzell Innerrhoden",
    BL: "Basel-Landschaft",
    BS: "Basel-Stadt",
    BE: "Bern",
    FR: "Freiburg",
    GE: "Genf",
    GL: "Glarus",
    GR: "Graubünden",
    JU: "Jura",
    LU: "Luzern",
    NE: "Neuenburg",
    NW: "Nidwalden",
    OW: "Obwalden",
    SH: "Schaffhausen",
    SZ: "Schwyz",
    SO: "Solothurn",
    SG: "St. Gallen",
    TI: "Tessin",
    TG: "Thurgau",
    UR: "Uri",
    VD: "Waadt",
    VS: "Wallis",
    ZG: "Zug",
    ZH: "Zürich"
}

export const holidayTypes: Record<string, string> = {
    by_law: "gesetzlich",
    optional: "optional",
    partly_by_law: "teils gesetzlich"
}

type CantonHolidaysType = Record<string, Array<{ name: string; date: string | null; type: HolidayType }>>

export const cantonHolidays: CantonHolidaysType = {
    AG: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.partly_by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.partly_by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.partly_by_law }
    ],
    AR: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    AI: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    BL: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    BS: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    BE: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    FR: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.partly_by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    GE: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    GL: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    GR: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.partly_by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    JU: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    LU: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Josefstag", date: "03-19", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    NE: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    NW: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    OW: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    SH: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    SZ: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    SO: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.partly_by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.partly_by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.partly_by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.partly_by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.partly_by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.partly_by_law }
    ],
    SG: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    TI: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    TG: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    UR: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Heilige Drei Könige", date: "01-06", type: HolidayType.by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ],
    VD: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    VS: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Josefstag", date: "03-19", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
    ],
    ZG: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Josefstag", date: "03-19", type: HolidayType.partly_by_law },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.optional },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.optional },
        { name: "Fronleichnam", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Mariä Himmelfahrt", date: "08-15", type: HolidayType.by_law },
        { name: "Allerheiligen", date: "11-01", type: HolidayType.by_law },
        { name: "Mariä Empfängnis", date: "12-08", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.optional }
    ],
    ZH: [
        { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
        { name: "Berchtoldstag", date: "01-02", type: HolidayType.optional },
        { name: "Karfreitag", date: null, type: HolidayType.by_law },
        { name: "Ostermontag", date: null, type: HolidayType.by_law },
        { name: "Tag der Arbeit", date: "05-01", type: HolidayType.by_law },
        { name: "Auffahrt", date: null, type: HolidayType.by_law },
        { name: "Pfingstmontag", date: null, type: HolidayType.by_law },
        { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
        { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law },
        { name: "Stephanstag", date: "12-26", type: HolidayType.by_law }
    ]
}

type NationHolidaysType = Array<{ name: string; date: string | null; type: HolidayType }>

export const nationalHolidays: NationHolidaysType = [
    { name: "Neujahrstag", date: "01-01", type: HolidayType.by_law },
    { name: "Karfreitag", date: null, type: HolidayType.partly_by_law },
    { name: "Auffahrt", date: null, type: HolidayType.by_law },
    { name: "Bundesfeier", date: "08-01", type: HolidayType.by_law },
    { name: "Weihnachtstag", date: "12-25", type: HolidayType.by_law }
]

export class Email {
    static general = "mail@andrin.software"
}
